# Legacy chat formatting has been deprecated.
# Please use Adventure's MiniMessage formatting: https://docs.advntr.dev/minimessage/format

# configuration of item metadata
items:
  invisible_item_frame:
    name: <!italic>Invisible Item Frame # what the name of the item should be
    enchantment_glint: true # if the item should have an enchantment glint

    # uncomment the below to assign lore text for the item
    #lore:
    #  - line1
    #  - line2

  invisible_glow_item_frame:
    name: <!italic>Invisible Glow Item Frame
    enchantment_glint: true

# configuration for crafting recipes
recipes:
  invisible_item_frame:

    # shape to use for the crafting recipe
    # - spaces are empty slots, and for a smaller than 3x3 recipe you can use a smaller grid
    # - letters are interpreted by the ingredients list below
    shape:
      - FFF
      - FAF
      - FFF

    # items required for crafting, matching the letters in the shape as defined above
    ingredients:
      F: minecraft:item_frame
      A: minecraft:phantom_membrane

    # how many of the item should be produced by the recipe.
    count: 8

  invisible_glow_item_frame:
    shape:
      - FFF
      - FAF
      - FFF
    ingredients:
      F: minecraft:glow_item_frame
      A: minecraft:phantom_membrane
    count: 8
