name: InvisibleItemFramesLite
version: ${project.version}
main: com.atlasgong.invisibleitemframeslite.InvisibleItemFramesLite
api-version: 1.21
description: Adds craftable invisible item frames for survival.
author: atlasgong
contributors: [ Tiffnix ]
website: "https://github.com/atlasgong/InvisibleItemFramesLite"
